default: &default
  pool: 5
  adapter: mysql2
  encoding: utf8
  host: 127.0.0.1
  username: root
  password:
  port: 3306

development:
  <<: *default
  database: mysite_development

test:
  <<: *default
  database: mysite_test

production:
  <<: *default
  database: mysite_production
