# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#



development:
  adapter: postgresql
  encoding: unicode
  database: web
  pool: 5


production:
  adapter: postgresql
  encoding: unicode
  database: web
  pool: 5

